name: Test

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ls
        uses: ./.github/actions/my-action
        # run: |
        #   chmod +x script.sh
        #   ./script.sh
        #   # echo "Hola Mundo" >> hola.txt
        #   # cat hola.txt
      