name: Hola mundo

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo "Hola Mundo"

    - name: touch file
      run: touch hola.txt

    - name: set text
      run: echo "Hola Mundo" > hola.txt

    - name: read file
      run: cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: LS
      run: ls -al

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: latest

    - name: node version
      run: node -v

    - name: Install
      run: npm install qwickjs

    - name: PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: PHP version
      run: php -v

  say-hello:
    runs-on: ubuntu-latest
    needs: [other]

    env:
      MY_VAR: Mi variable de entorno

    # services:
    #   mysql:
    #     image: mysql:5.7
    #     env:
    #       MYSQL_ROOT_PASSWORD: example
    #     ports:
    #       - "3306:3306"

    #   redis:
    #     image: redis:alpine
    #     ports:
    #       - "6379:6379"

    steps:
      - name: Test
        env:
          STEP_MY_VAR: Nivel step
        run: |
          echo "Valor: $MY_VAR"
          echo "Valor: $STEP_MY_VAR"
          echo "Valor: ${{ vars.MY_VAR_2 }}"

      - name: Secret
        run: |
          echo "Secret: ${{ secrets.MY_SECRET }}"